// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ybrzinhrlsasntnbpacz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlicnppbmhybHNhc250bmJwYWN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MzM0NDcsImV4cCI6MjA3MjMwOTQ0N30.L3PFtHTL8YmWmBQn0fa4sKllPUMGvaAYcJHfY1la-zQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});